apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-cron-1
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 15m" # valid cron schedule
  - name: direction
    value: "input"
  tracing:
    samplingRate: "1"
    stdout: true
    otel:
      endpointAddress: "otel-collector:4317"
      isSecure: false
      protocol: grpc
