apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configuration
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: "passwordadmin"
  - name: enableTLS
    value: false
