apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://useradmin:passwordadmin@rabbitmq:5672"
  # - name: protocol
  #   value: amqp
  # - name: hostname
  #   value: localhost
  # - name: username
  #   value: username
  # - name: password
  #   value: password
  # - name: consumerID # Optional: defaults to the app's own ID
  #   value: "{identifier}"
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 2
  - name: requeueInFailure
    value: false
  - name: prefetchCount
    value: 1
  - name: reconnectWait
    value: 3
  - name: concurrencyMode
    value: parallel
  - name: publisherConfirm
    value: true
  - name: enableDeadLetter # Optional enable dead Letter or not
    value: true
  - name: maxLen # Optional max message count in a queue
    value: 3000
  - name: maxLenBytes # Optional maximum length in bytes of a queue.
    value: 10485760
  - name: exchangeKind
    value: fanout
  - name: saslExternal
    value: false
  - name: ttlInSeconds
    value: 60
