apiVersion: 1

datasources:
  - id: 1
    uid: ff27wqg5o0zk0a
    orgId: 1
    name: prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/plugins/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus:9090
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      pdcInjected: false
      prometheusType: Prometheus
      prometheusVersion: 2.50.1
    readOnly: false
  - id: 2
    uid: cf27wtjwozrwga
    orgId: 1
    name: loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/plugins/loki/img/loki_icon.svg
    access: proxy
    url: http://loki:3100
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      pdcInjected: false
    readOnly: false
  - id: 3
    uid: cf27wuf6n82yoc
    orgId: 1
    name: tempo
    type: tempo
    typeName: Tempo
    typeLogoUrl: public/plugins/tempo/img/tempo_logo.svg
    access: proxy
    url: http://tempo:3200
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      pdcInjected: false
      tracesToLogsV2:
        customQuery: false
        datasourceUid: cf27wtjwozrwga
      tracesToMetrics:
        datasourceUid: ff27wqg5o0zk0a
    readOnly: false
