networks:
  default:
    name: muge_network
    driver: bridge

services:

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.138.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317   # OTLP gRPC receiver
      - 4318:4318   # OTLP http receiver
    expose:
      - 1888        # pprof extension
      - 8888        # Prometheus metrics exposed by the Collector
      - 8889        # Prometheus exporter metrics
      - 13133       # health_check extension
      - 55679       # zpages extension
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
        tag: "otel-collector"
    restart: "unless-stopped"
    depends_on:
      - seq-ingestion
      - aspire-dashboard

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: ${SEQ_FIRSTRUN_ADMINUSERNAME}
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_FIRSTRUN_ADMINPASSWORD}
    volumes:
      - ~/.docker/volumes/seq/data:/data
    ports:
      - "5341:5341"
      - "15341:80"
    restart: "unless-stopped"

  seq-ingestion:
    container_name: "seq-ingestion"
    image: datalust/seq-input-gelf:latest
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
    depends_on:
      - seq

  aspire-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    environment:
      ASPIRE_DASHBOARD_FORWARDEDHEADERS_ENABLED: "true"
    ports:
      - "18888:18888"
    expose:
      - "18889"
    restart: "unless-stopped"

  placement:
    container_name: placement
    image: "daprio/dapr:1.16.1"
    command: ["./placement", "-port", "50005"]
    ports:
      - 50005:50005
