version: '3.8'

networks:
  muge_network:
    external: true

services:

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "16379:8001"
    volumes:
      - ~/.docker/volumes/muge/redis-insight/data:/db
    networks:
      - muge_network

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - "15432:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@email.internal
  #     - PGADMIN_DEFAULT_PASSWORD=passwordadmin
  #   networks:
  #     - muge_network

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express:latest
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=useradmin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=passwordadmin
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_BASICAUTH_USERNAME=useradmin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=passwordadmin
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - muge_network

  linqpad-dapr:
    container_name: linqpad-dapr
    image: "daprio/daprd:edge"
    ports:
      - "3601:3601"
      - "50002:50002"
    command: ["./daprd",
     "-placement-host-address", "placement:50005",
     "-components-path", "/components",
     "-app-id", "linqpad",
     "-dapr-http-port", "3601",
     "-dapr-grpc-port", "50002",
     "-app-port", "5000",
     "--app-channel-address", "host.docker.internal"
     ]
    volumes:
        - ./config/components:/components
        - ${APPDATA}/Microsoft/UserSecrets/LinqPad:/secrets:ro
        # - ${APPDATA}/Microsoft/UserSecrets/LinqPad:/root/.microsoft/usersecrets/LinqPad:ro
    # network_mode: "service:linqpad"
    networks:
      - muge_network
