version: '3.8'

networks:
  muge_network:
    external: true

services:

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "16379:8001"
    volumes:
      - ~/.docker/volumes/muge/redis-insight/data:/db
    networks:
      - muge_network

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - "15432:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@email.internal
  #     - PGADMIN_DEFAULT_PASSWORD=passwordadmin
  #   networks:
  #     - muge_network

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express:latest
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=useradmin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=passwordadmin
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_BASICAUTH_USERNAME=useradmin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=passwordadmin
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - muge_network

  linqpad-dapr:
    container_name: linqpad-dapr
    image: "daprio/daprd:edge"
    ports:
      - "3601:3601"
      - "50002:50002"
    command: ["./daprd",
     "-placement-host-address", "placement:50005",
     "-components-path", "/components",
     "-app-id", "linqpad",
     "-dapr-http-port", "3501",
     "-dapr-grpc-port", "50002",
     "-app-port", "5000",
     "--app-channel-address", "host.docker.internal",
     "--log-level", "debug",
     "--enable-api-logging", "true"
     ]
    volumes:
        - ./config/components/development:/components
        - "C:/.ignore/localstorage:/localstorage"
        - ${APPDATA}/Microsoft/UserSecrets/LinqPad:/secrets:ro
    # network_mode: "service:linqpad"
    networks:
      - muge_network


  # myapp:
  #   container_name: myapp
  #   image: myapp:latest
  #   # build: "~\Source\local\20230822\myproject\src\myapp"
  #   build:
  #     context: ../myapp
  #     dockerfile: ./src/myapp/Dockerfile
  #     args:
  #       - BUILD_CONFIGURATION=Release
  #   env_file:
  #     - .env
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=${DEV_CERTS_PASSWORD}
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #     - Logging__Console__FormatterName=json
  #     - Logging__Console__FormatterOptions__IncludeScopes=true
  #     - Logging__Console__FormatterOptions__UseUtcTimestamp=true
  #     - Logging__Console__FormatterOptions__TimestampFormat=yyyyMMddHHmmss
  #     - Logging__Console__FormatterOptions__JsonWriterOptions__Indented=false
  #     - PrometheusExporterHttpListener=http://+:80/
  #   ports:
  #     - "5000:80"
  #     - "5001:443"
  #   volumes:
  #     - ~/.aspnet/https:/https:ro
  #     - ${APPDATA}/Microsoft/UserSecrets/myapp:/root/.microsoft/usersecrets/myapp:ro
  #   # logging:
  #   #   driver: "gelf"
  #   #   options:
  #   #     gelf-address: "udp://host.docker.internal:12201"
  #   #     # tag: "first-logs"
  #   #     # max-size: "200k"
  #   #     # max-file: "10"
  #   #     # deploy:
  #   #     #   resources:
  #   #     #     limits:
  #   #     #       cpus: '0.25'
  #   #     #       memory: 256M
  #   #     #     reservations:
  #   #     #       cpus: '0.125'
  #   #     #       memory: 128M
  #   networks:
  #     - muge_network

  # myapp-dapr:
  #   image: "daprio/daprd:edge"
  #   command: ["./daprd",
  #    "-placement-host-address", "placement:50005",
  #    "-components-path", "/components",
  #    "-app-id", "myapp"
  #   #  "-app-port", "80",
  #   #  "-dapr-http-port", "3500"
  #   #  "-dapr-grpc-port", "50001"
  #    ]
  #   volumes:
  #       - "./config/components/development:/components"
  #       - "~/Source/local/20230822/secrets:/secrets"
  #       - "~/Source/local/20230822/localstorage:/localstorage"
  #       - "~/Source/local/20230822/appconfig:/appconfig"
  #   depends_on:
  #     - myapp
  #   network_mode: "service:myapp"
